### ISSUE TITLE
iGraph error in generating ppi network 

### ISSUE THREAD

**Issue by llniu** [GuiltyTargets/guiltytargets#2]
Hi! Thanks for the great tool! I got errors with iGraph while generating the ppi network [exampleData.zip](https://github.com/GuiltyTargets/guiltytargets/files/4348566/exampleData.zip). 

Error message: 

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/Users/xxx/projects/DrugTarget/guiltytargets/src/guiltytargets/pipeline.py", line 52, in run
    ppi_edge_min_confidence=ppi_edge_min_confidence,
  File "/Users/xxx/projects/DrugTarget/guiltytargets/src/guiltytargets/ppi_network_annotation/pipeline.py", line 35, in generate_ppi_network
    protein_interactions = parse_ppi_graph(ppi_graph_path, ppi_edge_min_confidence)
  File "/Users/xxx/projects/DrugTarget/guiltytargets/src/guiltytargets/ppi_network_annotation/parsers.py", line 36, in parse_ppi_graph
    graph = igraph.read(os.path.expanduser(path), format="ncol", directed=False, names=True)
  File "/Users/xxx/projects/DrugTarget/guiltytargets/env_gts/lib/python3.6/site-packages/igraph/__init__.py", line 4355, in read
    return Graph.Read(filename, *args, **kwds)
  File "/Users/xxx
[exampleData.zip](https://github.com/GuiltyTargets/guiltytargets/files/4348559/exampleData.zip)
/projects/DrugTarget/guiltytargets/env_gts/lib/python3.6/site-packages/igraph/__init__.py", line 2399, in Read
    return reader(f, *args, **kwds)
igraph._igraph.InternalError: Error at /Users/travis/build/igraph/python-igraph/vendor/source/igraph/src/foreign.c:244: Parse error in NCOL file, line 1 (syntax error, unexpected NEWLINE, expecting ALNUM), Parse error
```

Code:
```python
from guiltytargets.pipeline import run
input_directory = 'experiments/'
targets_path = 'experiments/known_targetID.csv'
ppi_graph_path = 'experiments/ppi_graph.csv'
dge_path = 'experiments/dge3.tsv'
auc_output_path = 'experiments/'
probs_output_path = 'experiments/'
max_padj = 0.05
lfc_cutoff = 1
entrez_id_name = 'Entrez id'
log_fold_change_name = 'Log fold change'
adjusted_p_value_name = 'Adjusted p value'
base_mean_name = 'Base mean'
split_char = ';'
confidence_cutoff = 0.6
```

Data example: attached .zip file 
Not sure if the attach worked

**Comment by cthoyt** [comment]
From the error message it looks like there's an issue with the format of your input files. Would you attach them?

**Comment by llniu** [comment]
The attachment worked. Check the first line of my post :)

**Comment by cthoyt** [comment]
Your files are in the wrong format. It looks like your known target and PPI graph files both have index columns.

Maybe this is the result of exporting from pandas? I always use `df.to_csv(my_path, sep='\t', index=False)` to avoid this

**Comment by llniu** [comment]
Thanks! Removing the index column helped, had to also remove column headers from the PPI graph file and known target file. 

I ran into another error but managed to fix it:
In GAT2VEC/parsers.py, line 28, .as_matrix function has been deprecated and I changed it to .to_numpy(), it's running now.

```
    #return df.as_matrix(columns=df.columns[0:])
    return df.to_numpy()
```

**Comment by cthoyt** [comment]
Would you please send that as a PR? Then you can get sweet, sweet PR cred :)

**Comment by llniu** [comment]
Haha. It's rather an issue in the GAT2VAC package after installing - so nothing to be changed in your code I think. 
And the code ran through :)

**Comment by cthoyt** [comment]
Okay. We actually have [a fork of GAT2VEC](https://github.com/ozlemmuslu/GAT2VEC) that we use since the original code didn't work so well and had lots of bugs. We made a PR to the original authors (https://github.com/snash4/GAT2VEC/pull/2) but they were unresponsive... maybe it would have been a better idea to completely reimplement it 🤣
